name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    
    environment: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to GitLab
      uses: docker/login-action@v3
      with:
        registry: registry.cn-zhangjiakou.aliyuncs.com
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: |
        docker pull node:18-bullseye
        docker tag node:18-bullseye registry.cn-zhangjiakou.aliyuncs.com/top-sequence/node:18-bullseye
        docker push registry.cn-zhangjiakou.aliyuncs.com/top-sequence/node:18-bullseye
